# Generated by Django 4.2.7 on 2023-11-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='ehealth/images/doctors/'),
        ),
    ]
