# Generated by Django 4.2.7 on 2023-11-28 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form', models.CharField(choices=[('tablet', 'tablet'), ('injections', 'injections'), ('suspension', 'suspension')], max_length=255)),
                ('strenght', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date', 'date')},
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('medicaments', models.ManyToManyField(to='chat.medicament')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescript', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date', 'date'),
            },
        ),
    ]
