# Generated by Django 4.2.7 on 2023-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_medicament_alter_message_options_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='form',
            field=models.CharField(choices=[('tablet', 'tablet'), ('injections', 'injections'), ('suspension', 'suspension'), ('capsule', 'capsule')], max_length=255),
        ),
    ]
